name: 'Create SSH credentials'
description: 'Action to generate keystore and truststore for aiven.'
inputs:
  service_key_path:
    description: 'SSM path to service.key text.'
    required: true
  service_cert_path: 
    description: 'SSM path to service.cert text.'
    required: true
  keystore_password_path: 
    description: 'SSM path to keystore password.'
    required: true
  truststore_password_path: 
    description: 'SSM path to truststore password'
    required: true
  service_ca_path:  
    description: 'SSM path to ca.pem text.'
    required: true
  aws_access_key_id:
    description: 'AWS ACCESS KEY ID'
    required: true
  aws_secret_access_key:
    description: 'AWS SECRET ACCESS KEY'
    required: true
  aws_role_to_assume:
    description: 'ROLE TO ASSUME'
    required: true
  aws_default_region:
    description: 'AWS DEFAULT REGION'
    required: true
  working_directory:
    description: 'Directory in which files will be put'
    required: true
outputs:
  keystore_location:
    description: "Path to keystore"
    value: '${{ inputs.working_directory }}/client.keystore.p12'
  truststore_location:
    description: "Path to truststore"
    value: '${{ inputs.working_directory }}/client.truststore.jks'
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_default_region }}
        role-to-assume: ${{ inputs.aws_role_to_assume }}
        role-duration-seconds: 1200
        role-skip-session-tagging: true
    - run: ${{ github.action_path }}/entrypoint.sh
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env: 
          SERVICE_CERT_PATH: ${{ inputs.service_cert_path }}
          SERVICE_KEY_PATH: ${{ inputs.service_key_path }}
          CA_PATH: ${{ inputs.service_ca_path }}
          KEYSTORE_PASSWORD_PATH: ${{ inputs.keystore_password_path }}
          TRUSTSTORE_PASSWORD_PATH: ${{ inputs.truststore_password_path }}
